on:
  push:
    branches:
      - live

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to Public Documentation to Production
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: '*'
          remote_path: ${{ secrets.SRV_REMOTE_PATH }}
          args: '-o ConnectTimeout=5'